### ISSUE TITLE
Clarify wording on the distro sorting

### ISSUE THREAD

**Issue by mestaritonttu** [aviwad/librehunt#15]
Currently the string we see is:

> All distros matching even a little of what you said are here, ordered ascending to what is the most similar to what you wanted to what is the most dissimilar

I don't understand what this means. Did you mean to say "ascending from" instead, meaning that we see the most similar ones at the top? In that case, maybe "descending" would be better, as in descending from peak similarity?

**Comment by aviwad** [comment]
That is true. I should've used descending instead. I swear I used that long ago, maybe I changed it in some commit? I have no idea.

Nonetheless, I have exams this month, so I'll fix this in June :)
