### ISSUE TITLE
Instead of "match/not match" show actually criteria

### ISSUE THREAD

**Issue by rugk** [aviwad/librehunt#18]
![image](https://user-images.githubusercontent.com/11966684/58379731-ec2aba80-7fa7-11e9-84de-d988182da999.png)

You get this e.g..

Problem: The user has to remember what they selected for each criteria.

Proposed solution: Instead of showing just "match/not match" please show the criteria again, i.e. what the distro is like.
Then just show the tick or so next to it, if it matches.

Here is a mockup, how I would like to see it, e.g.
![image](https://user-images.githubusercontent.com/11966684/58379874-c7374700-7fa9-11e9-8f50-01803e12b42a.png)

Maybe you can drop the `something: yes` syntax altogether, and just say "Touch supported ✅".

And in case of the user choosing "I don't care", you may just show **no icon at the end** altogether.

**Comment by aviwad** [comment]
I will work on this tomorrow

**Comment by aviwad** [comment]
done
