### ISSUE TITLE
Remove "Extreme security" from questions

### ISSUE THREAD

**Issue by rugk** [aviwad/librehunt#20]
IMHO you should remove that.

It's just that if you want _extreme_ security, there are really not a lot of options. And if a user selects this (and they are a whisleblower or so :open_mouth:) they really should not choose any other criteria over their decision of a secure distro.

IMHO, in such a case it is **only** reasonable to recommend distros like Qubes OS or Tails. See computefreely's category [on security](https://computefreely.org/tags/security/).

Remember: If users choose this, they may be in bigger troubles than whether their "old hardware" works. It either works or not.

**Comment by rugk** [comment]
Proposed solutions:
* Maybe ask this question **at the beginning**  and if so, just redirect to the three distro's directly.
* Or remove the whole question and add a statement at the bottom below: "Do you need extreme security and your choice could endanger you? Click here."

Maybe also mention that this tool is then not really suited for "you". So users were this choice could be a live-endangering choice, should probably not use this tool and instead seek professional advise or so.

**Comment by aviwad** [comment]
will work on this after 2 days

**Comment by rugk** [comment]
It's still asked for me on the website.

**Comment by aviwad** [comment]
I forgot to remove the slide. Now it's properly fixed.
