### ISSUE TITLE
Add "Doesn't Matter" choice under Appearances

### ISSUE THREAD

**Issue by rdmarsee** [aviwad/librehunt#26]
Like the title says.
I find that I, or anyone who I recommend this tool to, seldom exclusively want either only a customized desktop or not. More often than not, this selection does not matter.

Thanks!

**Comment by aviwad** [comment]
Will work on this after a week (once my exams end)

Please do reply back here after a week, or I might forget :sweat_smile:

**Comment by aviwad** [comment]
Hi! Working on this, this week.

**Comment by rdmarsee** [comment]
Thanks for the update, and thank you for taking my suggestion on board :)
