### ISSUE TITLE
Results appear to be entirely random and unordered

### ISSUE THREAD

**Issue by slimelia** [aviwad/librehunt#45]
Answering questions in the same way produces different results every time. The results are also not ordered by best match, or in any order at all.

**Comment by aviwad** [comment]
The original list of distributions is shuffled. Then my recommendation algorithm assigns a 0 or 1 for each user value that the distribution satisfies/doesn't. Finally, the 0s and 1s are added up and the list of selected distributions is sorted by maximum total of 1s. So while the results may be "shuffled" it has not produced irrelevant answers, not in my experience at least. If you have a screenshot / screenrecording of librehunt recommending completely unrelated distributions I'd love to take a look. In my experience the 20 distributions suggested almost always have at least 3 user options ticked

**Comment by aviwad** [comment]
ok i do notice that the appearance lookalike option (mac/windows) is not respected properly.

**Comment by slimelia** [comment]
Oh, I wasn't aware the results got shuffled! I've had results where the first distro in the list only matches 2 or 3 of the criteria requested, and items that match all requested criteria appear halfway down the page. It's not stated anywhere that the results are shuffled, and in fact is stated that "all distros found are ordered descending from peak similarity". So maybe not an error in the code but an error in the language 😉

With the screenshot below, the expected behaviour based on the description that "all distros found are ordered descending from peak similarity" is that Fedora would appear first instead of sixth! 😅
![Screen Shot 2024-02-29 at 23 38 08](https://github.com/aviwad/librehunt/assets/19677816/07ff71b2-cb97-4725-bbfe-1dfc35fbfa1b)

**Comment by aviwad** [comment]
Yeah this is definitely unintuitive behavior. I haven't touched this codebase in ~5 years but i'll take a look at it this weekend. Keeping this issue open till then. Thanks for letting me know!

**Comment by aviwad** [comment]
can't believe this issue had been happening since my site launched. amazing haha. i believe it's fixed now. thanks a lot!
