### ISSUE TITLE
Website says "Invalid SSL certificate"

### ISSUE THREAD

**Issue by EarldridgeJazzedPineda** [aviwad/librehunt#50]
As of 5 December 2024, https://librehunt.org/ shows a Cloudflare "Invalid SSL certificate" page.
![2024-12-05-13-19-37-https-librehunt-org](https://github.com/user-attachments/assets/e7a16e17-ad6f-42ca-a3ac-5c9e48470495)

**Comment by EarldridgeJazzedPineda** [comment]
For now, I created a mirror of Librehunt at https://earldridgejazzedpineda.github.io/librehunt/

**Comment by aviwad** [comment]
ah shit just saw this. must be related to me switching the domain name provider to cloudfare. will take a look. thank you for hosting the mirror.

**Comment by aviwad** [comment]
disabled cloudfare's proxy services. fixed 😁 thank you for reporting!
